### ISSUE TITLE
PIP release

### ISSUE THREAD

**Issue by troopcat** [kadir014/turkishlang#1]
It would be great to have this library in pip.

**Comment by kadir014** [comment]
**TL;DR** No, the project is not maintained anymore. Just clone the repo and use it however you want.

As stated in the README, this project serves two solutions for two different problems. One being a new string type that supports Turkish characters and their methods, other one is a morphological parser which **is not finished** and probably will not be finished any time soon. 
So if you just want to use TurkishString, copy the `alphabet.py` module in your working directory,
